# Generated by Django 3.1.14 on 2023-07-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonabilitypokemon',
            name='slot',
            field=models.IntegerField(default=0),
        ),
    ]
