# Generated by Django 3.1.14 on 2023-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pokemonabilitypokemon_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='last_detail_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
